# -*- coding: utf-8 -*-
"""data_preprocess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q_Lqz5q6PSReJWQMwYo_bVjjFolcfKhS
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/sample_data/train.csv")

df.isnull().sum()

df.isnull().sum().sum()

df1=df.dropna(axis=1)
df1

df2=df.dropna(axis=0)
df2

df3=df.drop("Survived",axis=1)
df3

df8 = pd.DataFrame({"Age": [3, 15, 67, 55, 1, 29, 75, 89, 4, 10, 15, 38, 22, 77]})
df8['Label'] = pd.cut(x=df8["Age"], bins=[0, 3, 17, 63, 99], labels=["Baby/Toddler", "Child", "Adult", "Elderly"])
df8
print(df['Label'].value_counts())

df=pd.read_csv("/content/sample_data/IRIS.csv")
df

print(df["species"].unique())

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df["species"]= label_encoder.fit_transform(df["species"])
df["species"].unique()

df

# example of a ordinal encoding
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder 
# define data
data = asarray([["red"], ["green"], ["blue"]])
print(data)
# define ordinal encoding
encoder = OrdinalEncoder()
# transform data
result = encoder.fit_transform(data)
print(result)